version: '3.8'
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<your_password_here>
      - POSTGRES_DB=maybe_someone_returned_a_ticket
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local